# Generated by Django 5.0.1 on 2024-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(related_name='exerciseVideos', to='frontend.video')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(related_name='workoutPlaylists', to='frontend.playlists'),
        ),
    ]
