# Generated by Django 5.0.1 on 2024-04-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_playlists_user_playlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.playlists')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.video')),
            ],
            options={
                'unique_together': {('playlist', 'order')},
            },
        ),
    ]
