# Generated by Django 5.0.1 on 2024-04-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_playlistvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='exercises',
            field=models.ManyToManyField(related_name='exerciseVideos', to='frontend.playlistvideo'),
        ),
    ]
