# Generated by Django 5.0.1 on 2024-04-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_playlists_exercises'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistvideo',
            unique_together=set(),
        ),
    ]
