# Generated by Django 5.0.1 on 2024-04-25 12:07

import django.db.models.deletion
import frontend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_playlistvideo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='user',
            field=models.ForeignKey(default=frontend.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='userPlaylists', to=settings.AUTH_USER_MODEL),
        ),
    ]
