const Videos = {
    'male-barbell-bench-press-side_KciuhbB.mp4': require('./male-barbell-bench-press-side_KciuhbB.mp4'),
    'male-Barbell-barbell-incline-bench-press-side.mp4': require('./male-Barbell-barbell-incline-bench-press-side.mp4'),
    'male-barbell-overhead-press-side_1DIUbfS.mp4': require('./male-barbell-overhead-press-side_1DIUbfS.mp4'),
    'male-Bodyweight-dips-side.mp4': require('./male-Bodyweight-dips-side.mp4'),
    'male-Bodyweight-elevated-pike-press-side.mp4': require('./male-Bodyweight-elevated-pike-press-side.mp4'),
    'male-Bodyweight-push-up-side.mp4': require('./male-Bodyweight-push-up-side.mp4'),
    'male-cable-chestpress-side.mp4': require('./male-cable-chestpress-side.mp4'),
    'male-cable-pec-fly-side.mp4': require('./male-cable-pec-fly-side.mp4'),
    'male-Cables-cable-lateral-raise-side.mp4': require('./male-Cables-cable-lateral-raise-side.mp4'),
    'male-chest-stretch-variation-1-side.mp4': require('./male-chest-stretch-variation-1-side.mp4'),
    'male-chest-stretch-variation-2-side.mp4': require('./male-chest-stretch-variation-2-side.mp4'),
    'male-chest-stretch-variation-3-side.mp4': require('./male-chest-stretch-variation-3-side.mp4'),
    'male-bodyweight-hand-side-plank-front.mp4': require('./male-bodyweight-hand-side-plank-front.mp4'),
    'male-Dumbbells-dumbbell-russian-twist-side.mp4': require('./male-Dumbbells-dumbbell-russian-twist-side.mp4'),
    'male-Kettlebells-kettlebell-windmill-front.mp4': require('./male-Kettlebells-kettlebell-windmill-front.mp4'),
    'male-cable-woodchopper-front.mp4': require('./male-cable-woodchopper-front.mp4'),
    'male-abdominals-stretch-variation-2-front.mp4': require('./male-abdominals-stretch-variation-2-front.mp4'),
    'male-abdominals-stretch-variation-3-front.mp4': require('./male-abdominals-stretch-variation-3-front.mp4'),
    'male-shoulders-stretch-variation-1-front.mp4': require('./male-shoulders-stretch-variation-1-front.mp4'),
    'male-shoulders-stretch-variation-3-front.mp4': require('./male-shoulders-stretch-variation-3-front.mp4'),
    'male-Dumbbells-dumbbell-curl-front.mp4': require('./male-Dumbbells-dumbbell-curl-front.mp4'),
    'male-Dumbbells-dumbbell-hammer-curl-front.mp4': require('./male-Dumbbells-dumbbell-hammer-curl-front.mp4'),
    'male-Barbell-barbell-reverse-curl-side.mp4': require('./male-Barbell-barbell-reverse-curl-side.mp4'),
    'male-biceps-stretch-variation-1-side.mp4': require('./male-biceps-stretch-variation-1-side.mp4'),
    'male-biceps-stretch-variation-2-side.mp4': require('./male-biceps-stretch-variation-2-side.mp4'),
    'male-bodyweight-chinup-front.mp4': require('./male-bodyweight-chinup-front.mp4'),
    'male-bodyweight-hand-plank-side_GnZ2NZh.mp4': require('./male-bodyweight-hand-plank-side_GnZ2NZh.mp4'),
    'male-Barbell-barbell-situp-side.mp4': require('./male-Barbell-barbell-situp-side.mp4'),
    'male-abdominals-stretch-variation-1-side.mp4': require('./male-abdominals-stretch-variation-1-side.mp4'),
    'male-abdominals-stretch-variation-4-front.mp4': require('./male-abdominals-stretch-variation-4-front.mp4'),
    'male-Barbell-barbell-squat-side.mp4': require('./male-Barbell-barbell-squat-side.mp4'),
    'male-machine-leg-extension-front.mp4': require('./male-machine-leg-extension-front.mp4'),
    'male-barbell-step-up-side.mp4': require('./male-barbell-step-up-side.mp4'),
    'male-quads-stretch-variation-1-front.mp4': require('./male-quads-stretch-variation-1-front.mp4'),
    'male-quads-stretch-variation-2-side.mp4': require('./male-quads-stretch-variation-2-side.mp4')
};

export default Videos;
