BEGIN TRANSACTION;
INSERT INTO "frontend_exercisetype" VALUES (1,'Muscle Builder');
INSERT INTO "frontend_exercisetype" VALUES (2,'Calisthenics');
INSERT INTO "frontend_exercisetype" VALUES (3,'Stretch');
INSERT INTO "frontend_musclegroup" VALUES (1,'Chest');
INSERT INTO "frontend_musclegroup" VALUES (2,'Shoulder');
INSERT INTO "frontend_musclegroup" VALUES (4,'Lower Back');
INSERT INTO "frontend_musclegroup" VALUES (5,'Tricep');
INSERT INTO "frontend_musclegroup" VALUES (7,'Bicep');
INSERT INTO "frontend_musclegroup" VALUES (8,'Outer Abdominals');
INSERT INTO "frontend_musclegroup" VALUES (9,'Elbow');
INSERT INTO "frontend_musclegroup" VALUES (10,'Upper Back');
INSERT INTO "frontend_musclegroup" VALUES (11,'Forearm');
INSERT INTO "frontend_musclegroup" VALUES (12,'Abdominals');
INSERT INTO "frontend_musclegroup" VALUES (13,'Quads');
INSERT INTO "frontend_video_muscles" VALUES (1,1,1);
INSERT INTO "frontend_video_muscles" VALUES (2,1,2);
INSERT INTO "frontend_video_muscles" VALUES (3,2,1);
INSERT INTO "frontend_video_muscles" VALUES (4,2,2);
INSERT INTO "frontend_video_muscles" VALUES (5,3,2);
INSERT INTO "frontend_video_muscles" VALUES (6,4,1);
INSERT INTO "frontend_video_muscles" VALUES (7,4,5);
INSERT INTO "frontend_video_muscles" VALUES (10,6,1);
INSERT INTO "frontend_video_muscles" VALUES (11,6,5);
INSERT INTO "frontend_video_muscles" VALUES (12,7,1);
INSERT INTO "frontend_video_muscles" VALUES (13,7,5);
INSERT INTO "frontend_video_muscles" VALUES (14,8,1);
INSERT INTO "frontend_video_muscles" VALUES (15,9,1);
INSERT INTO "frontend_video_muscles" VALUES (16,7,7);
INSERT INTO "frontend_video_muscles" VALUES (17,10,2);
INSERT INTO "frontend_video_muscles" VALUES (18,11,1);
INSERT INTO "frontend_video_muscles" VALUES (19,12,1);
INSERT INTO "frontend_video_muscles" VALUES (20,13,1);
INSERT INTO "frontend_video_muscles" VALUES (21,14,8);
INSERT INTO "frontend_video_muscles" VALUES (22,15,8);
INSERT INTO "frontend_video_muscles" VALUES (23,16,8);
INSERT INTO "frontend_video_muscles" VALUES (24,17,8);
INSERT INTO "frontend_video_muscles" VALUES (25,18,8);
INSERT INTO "frontend_video_muscles" VALUES (26,19,8);
INSERT INTO "frontend_video_muscles" VALUES (27,20,2);
INSERT INTO "frontend_video_muscles" VALUES (28,21,2);
INSERT INTO "frontend_video_muscles" VALUES (29,22,7);
INSERT INTO "frontend_video_muscles" VALUES (30,23,7);
INSERT INTO "frontend_video_muscles" VALUES (32,24,7);
INSERT INTO "frontend_video_muscles" VALUES (33,25,7);
INSERT INTO "frontend_video_muscles" VALUES (34,26,7);
INSERT INTO "frontend_video_muscles" VALUES (37,27,10);
INSERT INTO "frontend_video_muscles" VALUES (38,27,11);
INSERT INTO "frontend_video_muscles" VALUES (39,26,11);
INSERT INTO "frontend_video_muscles" VALUES (40,25,11);
INSERT INTO "frontend_video_muscles" VALUES (41,24,11);
INSERT INTO "frontend_video_muscles" VALUES (42,7,11);
INSERT INTO "frontend_video_muscles" VALUES (43,28,12);
INSERT INTO "frontend_video_muscles" VALUES (44,29,12);
INSERT INTO "frontend_video_muscles" VALUES (45,30,12);
INSERT INTO "frontend_video_muscles" VALUES (46,31,12);
INSERT INTO "frontend_video_muscles" VALUES (47,32,13);
INSERT INTO "frontend_video_muscles" VALUES (48,33,13);
INSERT INTO "frontend_video_muscles" VALUES (49,34,13);
INSERT INTO "frontend_video_muscles" VALUES (50,35,13);
INSERT INTO "frontend_video_muscles" VALUES (51,36,13);
INSERT INTO "frontend_video_type" VALUES (1,1,1);
INSERT INTO "frontend_video_type" VALUES (2,2,1);
INSERT INTO "frontend_video_type" VALUES (3,3,1);
INSERT INTO "frontend_video_type" VALUES (4,4,2);
INSERT INTO "frontend_video_type" VALUES (6,6,2);
INSERT INTO "frontend_video_type" VALUES (7,7,2);
INSERT INTO "frontend_video_type" VALUES (8,8,1);
INSERT INTO "frontend_video_type" VALUES (9,9,1);
INSERT INTO "frontend_video_type" VALUES (10,10,1);
INSERT INTO "frontend_video_type" VALUES (11,11,3);
INSERT INTO "frontend_video_type" VALUES (12,12,3);
INSERT INTO "frontend_video_type" VALUES (13,13,3);
INSERT INTO "frontend_video_type" VALUES (14,14,2);
INSERT INTO "frontend_video_type" VALUES (16,16,1);
INSERT INTO "frontend_video_type" VALUES (18,17,1);
INSERT INTO "frontend_video_type" VALUES (19,15,2);
INSERT INTO "frontend_video_type" VALUES (20,18,3);
INSERT INTO "frontend_video_type" VALUES (21,19,3);
INSERT INTO "frontend_video_type" VALUES (22,20,3);
INSERT INTO "frontend_video_type" VALUES (23,21,3);
INSERT INTO "frontend_video_type" VALUES (24,22,1);
INSERT INTO "frontend_video_type" VALUES (25,23,1);
INSERT INTO "frontend_video_type" VALUES (26,24,1);
INSERT INTO "frontend_video_type" VALUES (27,25,3);
INSERT INTO "frontend_video_type" VALUES (28,26,3);
INSERT INTO "frontend_video_type" VALUES (29,27,2);
INSERT INTO "frontend_video_type" VALUES (30,28,2);
INSERT INTO "frontend_video_type" VALUES (31,29,2);
INSERT INTO "frontend_video_type" VALUES (32,30,3);
INSERT INTO "frontend_video_type" VALUES (33,31,3);
INSERT INTO "frontend_video_type" VALUES (34,32,1);
INSERT INTO "frontend_video_type" VALUES (35,33,1);
INSERT INTO "frontend_video_type" VALUES (36,34,1);
INSERT INTO "frontend_video_type" VALUES (37,35,3);
INSERT INTO "frontend_video_type" VALUES (38,36,3);
INSERT INTO "frontend_video_dangerous" VALUES (1,1,1);
INSERT INTO "frontend_video_dangerous" VALUES (2,1,2);
INSERT INTO "frontend_video_dangerous" VALUES (3,2,1);
INSERT INTO "frontend_video_dangerous" VALUES (4,2,2);
INSERT INTO "frontend_video_dangerous" VALUES (5,3,2);
INSERT INTO "frontend_video_dangerous" VALUES (6,3,4);
INSERT INTO "frontend_video_dangerous" VALUES (7,4,1);
INSERT INTO "frontend_video_dangerous" VALUES (8,4,5);
INSERT INTO "frontend_video_dangerous" VALUES (11,6,1);
INSERT INTO "frontend_video_dangerous" VALUES (12,6,5);
INSERT INTO "frontend_video_dangerous" VALUES (13,7,1);
INSERT INTO "frontend_video_dangerous" VALUES (14,8,1);
INSERT INTO "frontend_video_dangerous" VALUES (15,9,1);
INSERT INTO "frontend_video_dangerous" VALUES (16,10,2);
INSERT INTO "frontend_video_dangerous" VALUES (17,15,2);
INSERT INTO "frontend_video_dangerous" VALUES (18,16,9);
INSERT INTO "frontend_video_dangerous" VALUES (19,22,7);
INSERT INTO "frontend_video_dangerous" VALUES (20,23,7);
INSERT INTO "frontend_video_dangerous" VALUES (21,24,5);
INSERT INTO "frontend_video_dangerous" VALUES (22,27,10);
INSERT INTO "frontend_video_dangerous" VALUES (23,27,11);
INSERT INTO "frontend_video_dangerous" VALUES (24,27,4);
INSERT INTO "frontend_video_dangerous" VALUES (25,28,12);
INSERT INTO "frontend_video_dangerous" VALUES (26,29,12);
INSERT INTO "frontend_video_dangerous" VALUES (27,30,12);
INSERT INTO "frontend_video_dangerous" VALUES (28,31,4);
INSERT INTO "frontend_video_dangerous" VALUES (29,32,4);
INSERT INTO "frontend_video_dangerous" VALUES (30,32,13);
INSERT INTO "frontend_video_dangerous" VALUES (31,33,13);
INSERT INTO "frontend_video_dangerous" VALUES (32,34,13);
INSERT INTO "frontend_video_dangerous" VALUES (33,7,9);
INSERT INTO "frontend_equipment" VALUES (1,'Barbell');
INSERT INTO "frontend_equipment" VALUES (2,'Bench');
INSERT INTO "frontend_equipment" VALUES (3,'Cable Machine');
INSERT INTO "frontend_equipment" VALUES (4,'Dumbell');
INSERT INTO "frontend_equipment" VALUES (5,'Kettlebell');
INSERT INTO "frontend_equipment" VALUES (6,'Bar');
INSERT INTO "frontend_equipment" VALUES (7,'Bosu Ball');
INSERT INTO "frontend_equipment" VALUES (8,'Machine');
INSERT INTO "frontend_video_equipment" VALUES (1,1,1);
INSERT INTO "frontend_video_equipment" VALUES (2,1,2);
INSERT INTO "frontend_video_equipment" VALUES (3,2,1);
INSERT INTO "frontend_video_equipment" VALUES (4,2,2);
INSERT INTO "frontend_video_equipment" VALUES (5,3,1);
INSERT INTO "frontend_video_equipment" VALUES (6,8,3);
INSERT INTO "frontend_video_equipment" VALUES (7,9,3);
INSERT INTO "frontend_video_equipment" VALUES (8,10,3);
INSERT INTO "frontend_video_equipment" VALUES (9,15,4);
INSERT INTO "frontend_video_equipment" VALUES (10,16,5);
INSERT INTO "frontend_video_equipment" VALUES (11,17,3);
INSERT INTO "frontend_video_equipment" VALUES (12,22,4);
INSERT INTO "frontend_video_equipment" VALUES (13,23,4);
INSERT INTO "frontend_video_equipment" VALUES (14,24,1);
INSERT INTO "frontend_video_equipment" VALUES (15,27,6);
INSERT INTO "frontend_video_equipment" VALUES (16,29,1);
INSERT INTO "frontend_video_equipment" VALUES (17,31,7);
INSERT INTO "frontend_video_equipment" VALUES (18,32,1);
INSERT INTO "frontend_video_equipment" VALUES (19,33,8);
INSERT INTO "frontend_video_equipment" VALUES (20,34,1);
INSERT INTO "frontend_video" VALUES (1,'videos_uploaded/male-barbell-bench-press-side_KciuhbB.mp4','Barbell Bench Press','Lie on a bench with your feet on the ground, grip the barbell slightly wider than shoulder-width apart, and lift off the rack. Lower the barbell to your chest in a controlled manner, keeping your elbows tucked at a 45-degree angle. Press the barbell back up, exhaling as you push, and fully extend your arms without locking your elbows. Repeat for the desired number of repetitions, maintaining proper form throughout by keeping your shoulder blades retracted and a slight arch in your lower back.');
INSERT INTO "frontend_video" VALUES (2,'videos_uploaded/male-Barbell-barbell-incline-bench-press-side.mp4','Incline Barbell Bench Press','The incline barbell bench press is a variation of the traditional bench press that targets the upper chest muscles and shoulders. To perform it, adjust the bench to a 30-45 degree angle, lie back with your feet flat on the floor, and grip the barbell slightly wider than shoulder-width apart. Lift the bar off the rack, lower it to your upper chest with controlled movement, then press it back up, exhaling as you push. Keep your elbows tucked at a 45-degree angle and maintain a slight arch in your lower back.');
INSERT INTO "frontend_video" VALUES (3,'videos_uploaded/male-barbell-overhead-press-side_1DIUbfS.mp4','Barbell Overhead Press','Stand with your feet shoulder-width apart, grip the barbell with your hands just slightly wider than shoulder-width, and lift it to shoulder height, resting it on your collarbones. Press the barbell overhead by extending your arms, exhaling as you push, until your arms are fully extended above your head. Keep your core engaged, avoid arching your back excessively, and ensure that the barbell moves in a straight line.');
INSERT INTO "frontend_video" VALUES (4,'videos_uploaded/male-Bodyweight-dips-side.mp4','Dips','Find parallel bars or dip bars and grasp them with a firm grip. Lift yourself up, supporting your body weight with your arms fully extended and your elbows locked. Lean slightly forward and lower your body by bending your elbows until your upper arms are parallel to the ground or slightly below. Keep your elbows tucked in close to your body to target your triceps more effectively. Push yourself back up to the starting position by straightening your arms, exhaling as you press.');
INSERT INTO "frontend_video" VALUES (6,'videos_uploaded/male-Bodyweight-elevated-pike-press-side.mp4','Elevated Pike Press','Start in a push-up position with your feet elevated on a stable surface, such as a bench or box, and your hands on the ground slightly wider than shoulder-width apart. Lift your hips upward, forming an inverted "V" shape with your body, and walk your hands closer to your feet, bringing your torso closer to your thighs. This is the starting position. From here, lower your head towards the ground by bending your elbows, keeping them pointed out to the sides. Lower yourself until your head almost touches the ground between your hands. Then, press back up to the starting position by straightening your arms, exhaling as you push.');
INSERT INTO "frontend_video" VALUES (7,'videos_uploaded/male-Bodyweight-push-up-side.mp4','Push Up','Start in a plank position with your hands placed slightly wider than shoulder-width apart and your arms fully extended, fingers pointing forward or slightly outward. Your body should form a straight line from your head to your heels, engaging your core muscles to maintain stability. Lower your body towards the ground by bending your elbows, keeping them close to your sides, until your chest nearly touches the ground. Ensure that your back remains flat and your hips don''t sag or rise too high. Then, push yourself back up to the starting position by straightening your arms, exhaling as you push.');
INSERT INTO "frontend_video" VALUES (8,'videos_uploaded/male-cable-chestpress-side.mp4','Cable Chest Press','Stand in front of a cable machine with handles attached at chest height, grab the handles with an overhand grip, and step forward to create stability. Push the handles forward by extending your arms in front of you while keeping a slight bend in your elbows. Exhale as you press the handles away, squeezing your chest muscles at the end of the movement. Slowly return to the starting position, inhaling as you bring the handles back towards your chest in a controlled manner.');
INSERT INTO "frontend_video" VALUES (9,'videos_uploaded/male-cable-pec-fly-side.mp4','Cable Pec-Fly','Set the cable machine''s handles to the lowest position, and select an appropriate weight. Stand in the middle of the machine, grasp each handle, and step forward to create tension in the cables. Keep a slight bend in your elbows and maintain a stable stance. Bring your arms forward and together in a wide arc, squeezing your chest muscles at the peak of the movement. Exhale as you bring the handles together. Slowly return to the starting position, controlling the movement and inhaling as you do so.');
INSERT INTO "frontend_video" VALUES (10,'videos_uploaded/male-Cables-cable-lateral-raise-side.mp4','Cable Lateral Raises','Stand sideways to the machine, grab one handle with the hand closest to the machine, and step away to create tension in the cable. Keep a slight bend in your elbow and maintain a neutral spine. Raise your arm to the side in a wide arc until it''s parallel to the ground, exhaling as you lift. Focus on using your shoulder muscles to lift the weight.');
INSERT INTO "frontend_video" VALUES (11,'videos_uploaded/male-chest-stretch-variation-1-side.mp4','Chest Stretch One',NULL);
INSERT INTO "frontend_video" VALUES (12,'videos_uploaded/male-chest-stretch-variation-2-side.mp4','Chest Stretch Two','Lay on your side with the arm you are resting on placed just in front of you. With a slight bend in your arm, rotate your arm around your body as slowly as possible then return to the starting position.');
INSERT INTO "frontend_video" VALUES (13,'videos_uploaded/male-chest-stretch-variation-3-side.mp4','Chest Stretch Three','Place your arms behind your back and clasp your hands together. Slowly extend your elbows until they are locked then lift them away from you. Pause in this position for a few seconds and then return them to starting position.');
INSERT INTO "frontend_video" VALUES (14,'videos_uploaded/male-bodyweight-hand-side-plank-front.mp4','Hand Side Plank','Start by lying on your side with your legs extended and stacked on top of each other. Place your lower forearm on the ground directly below your shoulder, with your elbow bent at a 90-degree angle. Press into the ground with your forearm and lift your hips off the ground, creating a straight line from your head to your heels. Extend your opposite arm straight up towards the ceiling or place it on your hip for stability. Engage your core muscles to keep your body in a straight line and hold this position for the desired amount of time. Ensure that your hips stay lifted and don''t sag towards the ground.');
INSERT INTO "frontend_video" VALUES (15,'videos_uploaded/male-Dumbbells-dumbbell-russian-twist-side.mp4','Dumbbell Russian-Twist','Sit on the floor with your knees bent and your feet flat on the ground. Hold a dumbbell with both hands close to your chest, or without any weight if you''re a beginner. Lean back slightly to engage your core muscles. Lift your feet off the ground and balance on your glutes, creating a V-shape with your torso and thighs. Keeping your back straight, rotate your torso to the right, bringing the dumbbell towards the floor next to your right hip. Then, rotate your torso to the left, bringing the dumbbell towards the floor next to your left hip. Keep your core engaged and your movements controlled throughout the exercise.');
INSERT INTO "frontend_video" VALUES (16,'videos_uploaded/male-Kettlebells-kettlebell-windmill-front.mp4','Kettlebell Windmill','With a kettlebell in your right hand, arm extended above your shoulder. Turn your right foot out to about a 45-degree angle and keep your left foot facing forward. Engage your core and press the kettlebell overhead, keeping your arm straight. Next, hinge at your hips, pushing them back as you lean your torso to the left while keeping your right arm extended overhead. Lower your left hand towards the ground or your left shin while keeping your gaze on the kettlebell. Maintain a straight line from your right hand to your right foot. Pause at the bottom position, then reverse the movement, returning to the starting position by driving through your right foot and engaging your core.');
INSERT INTO "frontend_video" VALUES (17,'videos_uploaded/male-cable-woodchopper-front.mp4','Cable Woodchopper','Stand sideways to the machine with your feet shoulder-width apart and grasp the handle with both hands. Begin with your arms straight and positioned above your shoulder closest to the machine. Engage your core and rotate your torso away from the machine, pulling the handle diagonally downwards across your body towards the opposite hip in a chopping motion. Keep your arms extended and your core engaged throughout the movement. Slowly return to the starting position with control.');
INSERT INTO "frontend_video" VALUES (18,'videos_uploaded/male-abdominals-stretch-variation-2-front.mp4','Outer Abdominals Stretch One','Stand upright. Reach with both hands upwards until you can interlock your fingers. With your hands above your head, lean back until a stretch is felt in the abdominals.');
INSERT INTO "frontend_video" VALUES (19,'videos_uploaded/male-abdominals-stretch-variation-3-front.mp4','Outer Abdominals Stretch Two','Stand upright. After completing the desired amount of reps with the left arm, switch to the right arm and lean to the left. Reach up with your left arm and then lean slowly to the right. Lean until a stretch is felt in the obliques.');
INSERT INTO "frontend_video" VALUES (20,'videos_uploaded/male-shoulders-stretch-variation-1-front.mp4','Shoulder Stretch One','Reach one arm behind your body, with your elbow pointing upward behind your head. Assist the stretch with your other hand on your elbow to engage your shoulder. Pause for a few seconds, then repeat the stretch with your other arm.');
INSERT INTO "frontend_video" VALUES (21,'videos_uploaded/male-shoulders-stretch-variation-3-front.mp4','Shoulder Stretch Two','Place the top of your hand into the small of your back, your arm at a 90 degree angle. Hold your elbow with the other arm, and slowly pull the arm forward until you feel your shoulder engaged in the stretch. Pause at the apex of the stretch and return to the starting position. Return to starting position, and repeat with your other arm.');
INSERT INTO "frontend_video" VALUES (22,'videos_uploaded/male-Dumbbells-dumbbell-curl-front.mp4','Dumbell Curl','Keep your elbows close to your torso and your back straight. Engage your core muscles for stability. Keeping your upper arms stationary, exhale and curl the dumbbells upwards towards your shoulders by flexing your elbows, contracting your biceps. Focus on keeping your wrists straight and avoiding swinging or using momentum. At the top of the movement, squeeze your biceps briefly. Inhale as you slowly lower the dumbbells back to the starting position.');
INSERT INTO "frontend_video" VALUES (23,'videos_uploaded/male-Dumbbells-dumbbell-hammer-curl-front.mp4','Hammer Curl','Stand or sit with a dumbbell in each hand, palms facing inward towards your body, arms fully extended down by your sides. Keep your elbows close to your torso and your back straight. Engage your core muscles for stability. Without rotating your wrists, exhale and curl the dumbbells upwards towards your shoulders by flexing your elbows. Keep the movement controlled and focus on contracting your biceps and the muscles in your forearms. At the top of the movement, squeeze your muscles briefly. Inhale as you slowly lower the dumbbells back to the starting position');
INSERT INTO "frontend_video" VALUES (24,'videos_uploaded/male-Barbell-barbell-reverse-curl-side.mp4','Reverse Curl','Stand or sit with a dumbbell in each hand, arms fully extended down by your sides, palms facing down towards the floor. Keep your elbows close to your torso and your back straight. Engage your core muscles for stability. Without rotating your wrists, exhale and curl the dumbbells upwards towards your shoulders by flexing your elbows. Focus on keeping your wrists straight and contracting the muscles in your forearms. At the top of the movement, briefly squeeze your muscles. Inhale as you slowly lower the dumbbells back to the starting position');
INSERT INTO "frontend_video" VALUES (25,'videos_uploaded/male-biceps-stretch-variation-1-side.mp4','Bicep and Forearm Stretch One','Stand one foot in front of the other with the wall to your right, an arms width away. Place your hand on the wall, fingers pointing away from you. Gently lean forward, keeping your hand stationary. Repeat with the other arm.');
INSERT INTO "frontend_video" VALUES (26,'videos_uploaded/male-biceps-stretch-variation-2-side.mp4','Bicep and Forearm Stretch Two','Stand facing the wall, an arm''s width away. Place your hand on the wall with your fingers pointing down. Lean slightly into the wall to feel the stretch in your bicep.');
INSERT INTO "frontend_video" VALUES (27,'videos_uploaded/male-bodyweight-chinup-front.mp4','Chinup','Start by hanging from a pull-up bar with your palms facing towards you, hands shoulder-width apart or slightly narrower. Engage your core muscles and keep your shoulders down and back. Exhale as you pull yourself up towards the bar by bending your elbows, keeping them close to your body. Focus on using your back and arm muscles to lift your body until your chin clears the bar. Hold the top position for a moment, then inhale as you slowly lower yourself back down to the starting position');
INSERT INTO "frontend_video" VALUES (28,'videos_uploaded/male-bodyweight-hand-plank-side_GnZ2NZh.mp4','Plank','Start by lying face down on the floor or exercise mat. Position your elbows directly under your shoulders, with your forearms flat on the ground and your hands clasped together. Extend your legs straight behind you, toes tucked under, and engage your core muscles to lift your body off the ground, forming a straight line from your head to your heels. Keep your neck in line with your spine and your gaze towards the floor. Hold this position, focusing on maintaining a tight core and avoiding sagging or arching in your back.');
INSERT INTO "frontend_video" VALUES (29,'videos_uploaded/male-Barbell-barbell-situp-side.mp4','Barbell Situp','Start by lying flat on your back on an exercise mat or bench, with your knees bent and your feet flat on the floor. Hold a barbell plate securely against your chest with both hands, or position a barbell across your chest and hold it firmly in place. Engage your core muscles to lift your upper body off the ground, curling your torso towards your thighs. Keep your arms extended and the barbell plate or barbell steady against your chest. Continue to lift your upper body until your torso is in a seated position, with your back straight and your chest lifted. Slowly lower your upper body back down to the starting position with control, allowing your back to rest on the ground or bench.');
INSERT INTO "frontend_video" VALUES (30,'videos_uploaded/male-abdominals-stretch-variation-1-side.mp4','Abdominals Stretch One','Lay on your stomach on the floor with your forearms flat on the ground. Extend your elbows and push your upper body upwards. Push your upper body upwards until you feel a stretch in your abs, then return to the starting position and repeat.');
INSERT INTO "frontend_video" VALUES (31,'videos_uploaded/male-abdominals-stretch-variation-4-front.mp4','Abdominals Stretch Two','Lay on a ball or a Bosu ball with your feet firmly planted on the floor. Lean all the way back until you feel a stretch in your abdomen. Crunch upwards and hold for a 1-2 count. Slowly return to the starting position and repeat.');
INSERT INTO "frontend_video" VALUES (32,'videos_uploaded/male-Barbell-barbell-squat-side.mp4','Barbell Squat','Start by standing with your feet shoulder-width apart, the barbell resting on your upper traps or rear delts, and your hands gripping the bar wider than shoulder-width apart. Keeping your core engaged and chest up, initiate the movement by bending your knees and pushing your hips back, descending until your thighs are parallel to the ground. Ensure your knees track in line with your toes and maintain a neutral spine throughout. Drive through your heels to return to the starting position');
INSERT INTO "frontend_video" VALUES (33,'videos_uploaded/male-machine-leg-extension-front.mp4','Leg Extension','Sit on the machine with your back against the cushion and adjust the machine you are using so that your knees are at a 90 degree angle at the starting position. Raise the weight by extending your knees outward, then lower your leg to the starting position. Both movements should be done in a slow, controlled motion.');
INSERT INTO "frontend_video" VALUES (34,'videos_uploaded/male-barbell-step-up-side.mp4','Barbell Step Up Side','start by standing in front of a bench with a barbell positioned on your upper back, gripping it with hands wider than shoulder-width apart. Step onto the bench with one foot, driving through the heel to lift your body upward, and bringing the other foot to meet it on top of the bench. Lower yourself back down with control by stepping back with the foot that initially stepped up. Maintain proper form throughout, keeping your chest up, back straight, and knees tracking in line with your toes.');
INSERT INTO "frontend_video" VALUES (35,'videos_uploaded/male-quads-stretch-variation-1-front.mp4','Quad Stretch One','Stand perpendicular to a wall, using one arm against the wall for balance. With your other arm, grab the top of your foot. Pull your leg upwards and back to engage your quads, pausing at the apex of the stretch for a few seconds. Return to starting position and repeat with your other leg.');
INSERT INTO "frontend_video" VALUES (36,'videos_uploaded/male-quads-stretch-variation-2-side.mp4','Quad Stretch Two','Place one foot flat on the ground in front of you at a 90 degree angle. With your other leg, balance upon your knee, placing the tip of your foot against the wall behind you for balance. Place your hands on your knee in front of you, and lean forward so that your knee extends over your foot. Pause at the apex of the stretch, and slowly return to starting position. Repeat with your other leg.');
COMMIT;
