const IMAGES = {
    leftAbs: require('./leftabs.PNG'),
    leftBicep: require('./leftbicep.PNG'),
    leftChest: require('./leftchest.PNG'),
    leftForearm: require('./leftforearm.PNG'),
    leftLowerLeg: require('./leftlowerleg.PNG'),
    leftOuterAbs: require('./leftouterabs.PNG'),
    leftQuads: require('./leftquads.PNG'),
    leftShoulder: require('./leftshoulder.PNG'),
    rightAbs: require('./rightabs.PNG'),
    rightBicep: require('./rightbicep.PNG'),
    rightChest: require('./rightchest.PNG'),
    rightForearm: require('./rightforearm.PNG'),
    rightLowerLeg: require('./rightlowerleg.PNG'),
    rightOuterAbs: require('./rightouterabs.PNG'),
    rightQuads: require('./rightquads.PNG'),
    rightShoulder: require('./rightshoulder.PNG'),
    rightOutline: require('./Group 11/rightoutline.PNG'),
    leftOutline: require('./Group 11/leftoutline.PNG'),
    redLeftAbs: require('./redleftabs.PNG'),
    redLeftBicep: require('./redleftbicep.PNG'),
    redLeftChest: require('./redleftchest.PNG'),
    redLeftForearm: require('./redleftforearm.PNG'),
    redLeftOuterAbs: require('./redleftouterabs.PNG'),
    redLeftQuads: require('./redleftquads.PNG'),
    redLeftShoulder: require('./redleftshoulder.PNG'),
    redRightAbs: require('./redrightabs.PNG'),
    redRightBicep: require('./redrightbicep.PNG'),
    redRightChest: require('./redrightchest.PNG'),
    redRightForearm: require('./redrightforearm.PNG'),
    redRightOuterAbs: require('./redrightouterabs.PNG'),
    redRightQuads: require('./redrightquads.PNG'),
    redRightShoulder: require('./redrightshoulder.PNG'),
    greenLeftAbs: require('./greenleftabs.PNG'),
    greenLeftBicep: require('./greenleftbicep.PNG'),
    greenLeftChest: require('./greenleftchest.PNG'),
    greenLeftForearm: require('./greenleftforearm.PNG'),
    greenLeftOuterAbs: require('./greenleftouterabs.PNG'),
    greenLeftQuads: require('./greenleftquads.PNG'),
    greenLeftShoulder: require('./greenleftshoulder.PNG'),
    greenRightAbs: require('./greenrightabs.PNG'),
    greenRightBicep: require('./greenrightbicep.PNG'),
    greenRightChest: require('./greenrightchest.PNG'),
    greenRightForearm: require('./greenrightforearm.PNG'),
    greenRightOuterAbs: require('./greenrightouterabs.PNG'),
    greenRightQuads: require('./greenrightquads.PNG'),
    greenRightShoulder: require('./greenrightshoulder.PNG'),
};

export default IMAGES;
